name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -qq libgl-dev libglu1-mesa-dev python3 build-essential

      # Test fails with unable to find @python3/:bin/python3
      - name: Build
        run: bazel build //...

  test-darwin:
    runs-on: macos-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Test
        run: bazel test //...
