name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -qq libgl-dev libglu1-mesa-dev python3 build-essential libasound2-dev

      - name: Build
        run: bazel test //...

  test-darwin:
    runs-on: macos-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Test
        run: bazel test //...
